"""account confirmation

Revision ID: 56372de9bdd7
Revises: a551bdb1fb67
Create Date: 2016-04-22 18:45:34.226822

"""

# revision identifiers, used by Alembic.
revision = '56372de9bdd7'
down_revision = 'a551bdb1fb67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
