"""markdown

Revision ID: d6c889cabf74
Revises: 3a79c27ef974
Create Date: 2016-04-25 18:20:50.797392

"""

# revision identifiers, used by Alembic.
revision = 'd6c889cabf74'
down_revision = '3a79c27ef974'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
