"""catching_of_avatar_hashes

Revision ID: dee390e458ee
Revises: 46076aa55a46
Create Date: 2016-04-25 10:32:51.597541

"""

# revision identifiers, used by Alembic.
revision = 'dee390e458ee'
down_revision = '46076aa55a46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
